
import { 
  LayoutDashboard, 
  Users, 
  Package, 
  MapPin, 
  Recycle, 
  Award, 
  BarChart3, 
  Activity, 
  Settings,
  Bell,
  FileText,
  CheckSquare,
  Database,
  UserCog,
  UserCheck,
  Truck,
  Star,
  DollarSign,
  MessageSquare,
  Upload,
  Shield
} from "lucide-react";

export const adminTabList = [
  { id: "dashboard", label: "Dashboard", icon: LayoutDashboard },
  { id: "users", label: "Users", icon: Users },
  { id: "advanced-users", label: "User Mgmt", icon: UserCog },
  { id: "auth-management", label: "Auth Mgmt", icon: UserCheck },
  { id: "collection-scheduling", label: "Collection", icon: Truck },
  { id: "quality-assessment", label: "Quality", icon: Star },
  { id: "financial-management", label: "Financial", icon: DollarSign },
  { id: "communication-hub", label: "Communications", icon: MessageSquare },
  { id: "data-management", label: "Data Mgmt", icon: Upload },
  { id: "compliance", label: "Compliance", icon: Shield },
  { id: "inventory", label: "Inventory", icon: Package },
  { id: "centers", label: "Centers", icon: MapPin },
  { id: "waste-flow", label: "Waste Flow", icon: Recycle },
  { id: "credits", label: "Credits", icon: Award },
  { id: "analytics", label: "Analytics", icon: BarChart3 },
  { id: "monitoring", label: "Monitoring", icon: Activity },
  { id: "notifications", label: "Notifications", icon: Bell },
  { id: "reports", label: "Reports", icon: FileText },
  { id: "bulk-ops", label: "Bulk Ops", icon: CheckSquare },
  { id: "system-config", label: "Config", icon: Database },
  { id: "settings", label: "Settings", icon: Settings },
];
