// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cvccrejhpjwwnkxmgbrb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN2Y2NyZWpocGp3d25reG1nYnJiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDU5MjUsImV4cCI6MjA2NDI4MTkyNX0.JoEgeLo2wEAgHmmWkmSKPovG3s7P9bBX1JPTaLi0G7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);